config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  
  devise_scope :customer do
    get '/customers/sign_out' => 'devise/sessions#destroy'
  end
  
  devise_scope :admin do
    get '/admin/sign_out' => 'devise/sessions#destroy'
  end
  
  namespace :admin do
    get 'top' => 'homes#top', as: 'top'
    get 'search' => 'homes#search', as: 'search'
    get 'customers/:customer_id/orders' => 'orders#index', as: 'customer_orders'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:index, :show, :update] do
      resources :order_details, only: [:update]
    end
  end
  
  scope module: :public do
    root 'homes#top'
    get 'customers/mypage' => 'customers#show', as: 'mypage'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'confirm_unsubscribe'
    put 'customers/information' => 'customers#update'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw_customer'
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all_cart_items'
    post 'orders/confirm' => 'orders#confirm'
    get 'orders/confirm' => 'orders#error'
    get 'orders/thanks' => 'orders#thanks', as: 'thanks'

    resources :customers, only: [:index, :show]
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :items, only: [:index, :show] do
      resources :cart_items, only: [:create, :update, :destroy]
    end
    resources :cart_items, only: [:index]
    resources :orders, only: [:new, :index, :create, :show]
  end
  
   
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  has_one_attached :image
  
  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  validate :image_type

 scope :where_genre_active, -> { joins(:genre).where(genres: { is_active: true }) }
  
  def get_image(*size)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.png')
      image.attach(io: File.open(file_path), filename: 'no-image.png', content_type: 'image/png')
    end
    
    if !size.empty?
      image.variant(resize: size)
    else
      image
    end
  end
  
  def get_cut_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no-image.png')
      image.attach(io: File.open(file_path), filename: 'no-image.png', content_type: 'image/png')
    end
      image.variant(resize_to_fill: [256, 170]).processed
  end
    
  def with_tax_price
    (price * 1.1).ceil
    # ceilは切り上げ、floorが切り捨て、roundが四捨五入
  end

  def self.recommended
    recommends = []
    active_genres = Genre.only_active.includes(:items)
    active_genres.each do |genre|
      item = genre.items.last
      recommends << item if item
    end
    recommends
  end

  private
  
  def image_type
    if !image.blob
      errors.add(:image, 'をアップロードしてください')
    elsif !image.blob.content_type.in?(%('image/jpeg image/png'))
      errors.add(:image, 'はJPEGまたはPNG形式を選択してアップロードしてください')
    end
  end


end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  before_action :ensure_item, only: [:show, :edit, :update]

  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    @item.save ? (redirect_to admin_item_path(@item)) : (render :new)
  end

  def index
    if params[:genre_id]
      @genre = Genre.find(params[:genre_id])
      all_items = @genre.items
    else
      all_items = Item.includes(:genre)
    end
    @items = all_items.page(params[:page])
    @all_items_count = all_items.count
  end

  def show
  end

  def edit
  end
  
  def update
    @item.update(item_params) ? (redirect_to admin_item_path(@item)) : (render :edit)
  end
  
  private
  
  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :is_active, :image)
  end
  
  def ensure_item
    @item = Item.find(params[:id])
  end
  
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_form.html.erb
<%= form_with model:item, url: url do |f| %>
  <%= render 'layouts/error_messages', resource: item %>
  <div class="flex">
    <div>
    <%= f.label :image, "画像" %>
      <div class="image_field">
        <%= image_tag (item.image.attached? ? item.image : 'no-image.png'), id: "img_prev", class: "admin_item_image" %>
        <span class="btn btn-file btn-info"><%= f.file_field :image,  accept:'image/*' %>画像選択</span>
        <p>選択するとプレビューされます。<br>画像未選択のままだと、<br>「画像準備中」になります。</p>
      </div>
    </div>
    <table class="admin_item_info item_form">
      <thead>
        <tr>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= f.label :name, "商品名" %></td>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <td><%= f.label :introduction, "商品説明" %></td>
          <td><%= f.text_area :introduction, rows: 3 %></td>
        </tr>
        <tr>
          <td><%= f.label :genre_id, "ジャンル" %></td>
          <td class="select_field"><%= f.collection_select :genre_id, Genre.all, :id, :name %></td>
        </tr>
        <tr>
          <td><%= f.label :price, "税抜価格" %></td>
          <td><%= f.number_field :price %> 円</td>
        </tr>
        <tr>
          <td><%= f.label :sales_status, "販売ステータス" %></td>
          <td class="select_field">
            <%= f.radio_button :is_active, true %>
            <%= f.label :is_active, "販売中", class: "text-active" %>
            <%= f.radio_button :is_active, false %>
            <%= f.label :is_active, "販売停止中", class: "text-invalid" %>
          </td>
        </tr>
      </tbody>
    </table>
    <div class="flex align-center pl5">
      <%= f.submit submit, class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/admin/items/_index.html.erb
<table class="admin_items has_border">
  <thead>
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜価格</th>
      <th>ジャンル</th>
      <th>販売ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% items.each do |item| %>
      <tr>
        <td class="text-center"><%= item.id %></td>
        <td><%= link_to item.name, admin_item_path(item), class: "underline" %></td>
        <td class="text-center"><%= item.price %>円</td>
        <td><%= link_to item.genre.name, admin_items_path(genre_id: item.genre_id) %></td>
        <td>
          <% if item.is_active? %>
            <span class="text-active">販売中</span>
          <% else %>
            <span class="text-invalid">販売停止中</span>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/items/edit.html.erb
<section class="inner">
  <h2 class="section-ttl"><%= @item.name %>の編集</h2>
  <%= render 'form', item: @item, url: admin_item_path(@item), submit: '更新' %>
</section>

app/views/admin/items/index.html.erb
<section class="wrapper flex">
  <div class="inner">
    <% if params[:genre_id] %>
      <h2 class="section-ttl"><%= @genre.name %>の商品一覧 (全<%= @all_items_count %>件)</h2>
    <% else %>
      <h2 class="section-ttl">商品一覧 (全<%= @all_items_count %>件)</h2>
    <% end %>
      <h3 class="text-right">
        <%= link_to "+", new_admin_item_path, class: "new_admin_item" %>
      </h3>
    <% if @items.first %> <!-- @item.existsと同義、SQL1個分削減(?) -->
       <%= render 'admin/items/index', items: @items %>
      <%= paginate @items %>
    <% else %>
      <h3>対応する商品はありませんでした。</h3>
    <% end %>
  </div>
</section>

app/views/admin/items/new.html.erb
<section class="inner">
  <h2 class="section-ttl">商品新規登録</h2>
  <%= render 'form', item: @item, url: admin_items_path, submit: '登録' %>
</section>

app/views/admin/items/show.html.erb
<section class="inner">
  <h2 class="section-ttl">商品詳細</h2>
  <div class="flex">
    <div>
      <div class="image_field">
        <%= image_tag @item.get_image, id: "img_prev", class: "admin_item_image" %>
      </div>
    </div>
    <table class="admin_item_info">
      <thead>
        <tr>
          <th></th>	
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>商品名</td>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <td>商品説明</td>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <td>ジャンル</td>
          <td><%= link_to @item.genre.name, admin_items_path(genre_id: @item.genre_id), class: "underline" %></td>
        </tr>
        <tr>
          <td>税抜価格</td>
          <td><%= @item.price %>円</td>
        </tr>
        <tr>
          <td>販売ステータス</td>
          <td>
            <% if @item.is_active? %>
              <span class="text-active">販売中</span>
            <% else %>
              <span class="text-invalid">販売停止中</span>							
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
    <div class="flex align-center pl5">
      <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success" %>
    </div>
  </div>
</section>